openapi: 3.0.1
info:
  title: monster-shadow-demon
  x-cortex-tag: monster-shadow-demon
  x-cortex-custom-metadata:
    alignment: neutral-evil
    type: celestial
    challenge_rating: 8
    legendary: true
    armor_class: 11
    hit_points: 171
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-shadow-demon
      alias: github-token-test
